---

general_config:
  java_version: jdk-11.0.12_linux-x64_bin.tar.gz
  zookeeper_version: apache-zookeeper-3.5.9-bin.tar.gz
  kafka_version: kafka_2.13-2.8.0.tgz
  install_java: true
  install_zookeeper: true
  install_kafka: true
  create_data_kafka_disk: 
      present: true
      device: /dev/sdb
      filesystem: 'xfs' 
      vg_name: vg_kafka_data
      lv_name: lv_kafka_data
      lv_size: '100%FREE' 
      mount_point: /kafka/data
     
  
kafka_config:
        kafka_log: /var/log/kafka
        num_network_threads: 3
        num_io_threads: 8
        log_dirs: "{{ general_config.create_data_kafka_disk.mount_point }}"
        num_partitions: 3
        num_recovery_threads_per_data_dir: 3
        offsets_topic_replication_factor: 3
        transaction_state_log_replication_factor: 3 
        transaction_state_log_min_isr: 1 
        log_retention_hours: 24
        log_retention_check_interval_ms: 300000
        zookeeper_connection_timeout_ms: 6000
        group_initial_rebalance_delay_ms: 0
        auto_create_topics_enable: true
        leader_imbalance_check_interval_seconds: 5
        Xmx: 2
        Xms: 2
        jmx_port: 9999


zookeeper_config:
  zookeeper_admin_enableServer: false
  client_port: 2181
  dataDir: /var/lib/zookeeper
   



repo_info:
   protocol: http://
   url: repo.fwut.xyz
   port: 80

#  --------------- kafka nodes ----------------
kafka_nodes:
  node1:
    advertised_listeners: 10.29.0.104
    listeners: 10.29.0.104
    ssh_ip: 10.29.0.104
    port: 9092
    broker_id: 104
    
  node2:
    advertised_listeners: 10.29.0.105
    listeners: 10.29.0.105
    ssh_ip: 10.29.0.105
    port: 9092
    broker_id: 105
    
  node3:
    advertised_listeners: 10.29.0.106
    listeners: 10.29.0.106
    ssh_ip: 10.29.0.106
    port: 9092
    broker_id: 106
    

# ---------------- ZooKeeper nodes  --------------------10.29.0.106
zookeeper_nodes:
  node1: 
    ssh_ip: 10.29.0.104
    internal_ip: 10.29.0.104
    myid: 104
    port: 2181

  node2: 
    ssh_ip: 10.29.0.105
    internal_ip: 10.29.0.105
    myid: 105
    port: 2181

  node3: 
    ssh_ip: 10.29.0.106
    internal_ip: 10.29.0.106
    myid: 106
    port: 2181
    
