---
- name: Add td-agent GPG key.
  rpm_key:
    key: "{{ r_fluentd_fluentd_repo }}/GPG-KEY-td-agent"
    state: present

- name: Add td-agent repository.
  template:
    src: td.repo.j2
    dest: /etc/yum.repos.d/td.repo
    mode: 0644
