---
- name: Add required dependencies
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add td-agent apt key
  apt_key:
    url: "{{ r_fluentd_fluentd_repo }}/GPG-KEY-td-agent"
    state: present

- name: Add td-agent repository
  apt_repository:
    repo: 'deb {{ r_fluentd_fluentd_repo }}/'
    state: present
    update_cache: true
