---
- name: Load Variables
  tags: always
  block:
    - name: Load system variables
      include_vars:
        dir: ../vars/common
        ignore_unknown_extensions: yes
    - name: Populate facts var
      include_vars: ../vars/facts/{{ansible_connection}}.yml      
    - name: Loading OS variables
      include_vars:
        dir: "{{ item }}"
        name: os
      tags: load_os_vars
      loop: "{{ query('first_found', ['../vars/os/{{ facts.os_dist_ver }}.yml', '../vars/os/{{ facts.distro_lower }}/{{ facts.distro_major }}'], errors='ignore') }}"
    - name: Ensure OS variables are loaded
      assert:
        that: os is defined
        fail_msg: | 
          Could not load any OS variables!
          Paths:
            '../vars/os/{{ facts.os_dist_ver }}.yml'
            '../vars/os/{{ facts.distro_lower }}/{{ facts.distro_major }}'
      tags: ensure_os_vars
- name: Show variables
  debug:
    var: ansible_included_var_files
  tags: Loaded Vars
  when: "'Loaded Vars' in ansible_run_tags"
- name: Get Variable
  debug:
    var: "{{ var }}"
  tags: Get Var
  when:
    - "'Get Var' in ansible_run_tags"
    - var is defined
