---
- name: Deploy Firewall APP
  become: yes
  tags: r_AppFirewall
  block:
    - name: Include extra options
      include_vars:
        dir: vars
        ignore_files : main.yml
      tags: always
      
    - name: Include tasks for "{{ facts.distro }}"
      include_tasks:
        file: "{{ facts.distro_lower }}.yml"
        apply:
          tags: r_AppFirewall_os
      tags: r_AppFirewall_os

    - import_tasks: install.yml
      tags: r_AppFirewall_install

    - import_tasks: make_settings.yml
      tags: 
        - r_AppFirewall_config
        - firewall_config
        
    - import_tasks: test.yml
      tags: r_AppFirewall_test

    - name: CLEAN RULES
      tags:
        - never
        - r_AppFirewall_CLEAN_HOST_RULES
      block:
        - import_tasks: remove_rules.yml
          vars:
            - rules_version: v4
        - import_tasks: remove_rules.yml
          vars:
            - rules_version: v6

    - import_tasks: remove.yml
      tags:
        - never
        - ROLE_APP_FIREWALL_REMOVE