- name : "Become"
  become: yes
  block:
    - name: "Ensure working directory"
      file:
        path: "{{ g_src_path }}/{{ r_nextcloud_docker_project_path }}"
        state: directory

    - name: "Create prometheus docker-compose file"
      template:
        dest: "{{ g_src_path }}/{{ r_nextcloud_docker_project_path }}/docker-compose.yml"
        src: "docker-compose.j2"
        owner: ansible
        group: docker
        mode: 0755

    - name: "execute docker-compose to run nextcloud docker image"
      docker_compose:
        project_src: "{{ g_src_path }}/{{ r_nextcloud_docker_project_path }}"
        state: present
   