---
- name: enable nginx
  become: yes
  systemd:
    name: nginx
    enabled: yes
- name: restart nginx
  become: yes
  systemd:
    name: nginx
    state: restarted
- name: reload nginx
  become: yes
  systemd:
    name: nginx
    state: reloaded
- name: yum-clean-metadata
  become: yes
  command: yum clean metadata
  args:
    warn: no