---
# - name: Tear down existing services
#   docker_compose:
#     project_src: /opt/docker/test
#     state: absent
# - name: Create and start services
#   docker_compose:
#     project_src: /opt/docker/test
#   register: output
