# ---
- name: Network Configuration
  become: yes
  tags:
    - r_common_networking
  block:
    - name: Ensure base interface file
      template:
        src: debian/interfaces_main.j2
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: 0644
      vars:
        iface: lo
        net:
          up_mode: auto
          options:
            - "{{ debian_lo_v4|combine(ho_debian_lo_v4, recursive=True) }}"
            - "{{ debian_lo_v6|combine(ho_debian_lo_v6, recursive=True) }}"
      when:
        - networks is defined
        - not networks == {}
    - name: Config network interface
      template:
        src: "debian/interface.j2"
        dest: "/etc/network/interfaces.d/{{ item.key }}.conf"
      with_dict: "{{ networks|default({}) }}"
      loop_control:
        label: "{{ item.key }}"
        index_var: iface_id
      vars:
        net: "{{ item.value }}"
        iface: "{{ item.key }}"
      when: not item.value.disabled|default(False)|bool
      notify:
        - Restart Networking
    - name: Remove disabled networks
      file:
        path: "/etc/network/interfaces.d/{{item.key}}.conf"
        state: absent
      loop: "{{ networks|default({})|dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      when: item.value.disabled|default(False)|bool
      notify:
        - Restart Networking

- name: Configure ntp
  become: yes
  template:
    src: "debian/ntp.j2"
    dest: "/etc/ntp.conf"
  notify:
    - Restart Services 'ntp'
  tags:
    - r_common_ntp

- name: Pakcages Configuration
  become: yes
  tags:
    - r_common_packages
  block:
    - name: Setup APT repo
      include_tasks:
        file: apt_repo.yml
        apply:
          tags: r_common_packages
      vars:
        repo_list: "{{ os.repositories.default|combine(ho_debian_local_repos, ho_debian_repos, recursive=True) }}"
    - name: Update repo cache
      apt:
        update_cache: yes

# # - name: Services Configuration
# #   become: yes
# #   block:
# #     - name: Ensure sshd selinux custom port
# #       seport:
# #         ports: "{{ sshd_port | mandatory }}"
# #         proto: tcp
# #         setype: ssh_port_t
# #         state: present
# #       notify: Restart ssh
# #     - name: rsyslog configuration
# #       copy:
# #         src: centos/rsyslog.d/
# #         dest: /etc/rsyslog.d
# #   tags:
# #     - services