---
- name: Network Configuration
  become: yes
  tags: r_common_networking
  block:
    - name: Config network interface
      template:
        src: "centos/ifcfg.j2"
        dest: "/etc/sysconfig/network-scripts/ifcfg-{{item.key}}"
      loop: "{{ networks|default({})|dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      when: not item.value.disabled|default(False)|bool
      notify:
        - Restart Networking
    - name: Remove disabled networks
      file:
        path: "/etc/sysconfig/network-scripts/ifcfg-{{item.key}}"
        state: absent
      loop: "{{ networks|default({})|dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      when: item.value.disabled|default(False)|bool
      notify:
        - Restart Networking

- name: Configure ntp
  become: yes
  tags: r_common_extra
  template:
    src: "centos/chrony.j2"
    dest: "/etc/chrony.conf"
  notify:
    - Restart Services 'ntp'

- name: Pakcages Configuration
  become: yes
  tags: r_common_pakcages
  block:
    - name: Use proxy for yum
      lineinfile:
        path: /etc/yum.conf
        regexp: 'proxy=.*'
        line: "proxy={{ proxy.http }}"
      when:
        - proxy.http is defined
        - ho_yum_use_proxy
    - name: Install Oracle Linux packages
      yum:
        name: "{{ item }}"
        state: installed
      loop: "{{ os.packages.oraclelinux_common|default({}) }}"

- name: Services Configuration
  become: yes
  tags: r_common_services
  block:
    - name: Ensure sshd selinux custom port
      seport:
        ports: "{{ sshd_port | mandatory }}"
        proto: tcp
        setype: ssh_port_t
        state: present
      notify: Restart Services 'ssh'
    - name: rsyslog configuration
      copy:
        src: centos/rsyslog.d/
        dest: /etc/rsyslog.d
