---
- name: Apply system user
  become: yes
  when: system_user is defined
  block:
    - name: Active user "{{ system_user.key }}"
      include_tasks: Play_sysAdmin/SystemUsers/apply.yml
      when:
        - system_user.value.active|default(True)
        - inventory_hostname is search(system_user.value.access_list) or group_names is search(system_user.value.access_list)
    - name: Inactive user "{{ system_user.key }}"
      include_tasks: Play_sysAdmin/SystemUsers/remove.yml
      when: not system_user.value.active|default(True) or not (inventory_hostname is search(system_user.value.access_list) or group_names is search(system_user.value.access_list))        