---
- name: Add Elasticsearch GPG key.
  rpm_key:
    key: "{{ r_kibana_kibana_repo }}/GPG-KEY-elasticsearch"
    state: present

- name: Add Kibana repository.
  template:
    src: kibana.repo.j2
    dest: /etc/yum.repos.d/kibana.repo
    mode: 0644
