---
- name: Ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add Elasticsearch apt key.
  apt_key:
    url: "{{ r_kibana_kibana_repo }}/GPG-KEY-elasticsearch"
    state: present

- name: Add Kibana repository
  apt_repository:
    repo: 'deb {{ r_kibana_kibana_repo }}/'
    state: present
    update_cache: true
