---
- name: Deploy kibana
  become: yes
  block:
  # - name: Include tasks for "{{ facts.os_info }}"
  #   include_tasks: "{{ facts.distro_lower }}.yml"

  - name: Install Kibana
    package:
      name: kibana
      state: present

  - name: Start Kibana
    systemd:
      name: kibana
      state: started
      enabled: yes

  - name: Copy Kibana configuration
    template:
      src: kibana.yml.j2
      dest: "/etc/kibana/kibana.yml"
      owner: root
      group: root
      mode: 0644
    notify: restart kibana    