---
- name: setup Debian
  become: yes
  block:
  - name: Ensure PostgreSQL Python libraries are installed.
    apt:
      name: "{{ r_postgresql_postgresql_python_library }}"
      state: present

  - name: Ensure PostgreSQL packages are installed.
    apt:
      name: "{{ r_postgresql_postgresql_packages }}"
      state: present

  - name: Ensure all configured locales are present.
    locale_gen: 
      name: "{{ item }}"
      state: present
    with_items: "{{ r_postgresql_postgresql_locales }}"
    register: locale_gen_result

  - name: Force-restart PostgreSQL after new locales are generated.
    service:
      name: "{{ r_postgresql_postgresql_daemon }}"
      state: restarted
    when: locale_gen_result.changed
