---
- name: Ensure PostgreSQL users are configured correctly.
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ example_user_pass | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    db: "{{ item.db | default(omit) }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(r_postgresql_postgresql_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(r_postgresql_postgresql_unix_socket_directories[0]) }}"
    port: "{{ item.port | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_users }}"
  no_log: "{{ r_postgresql_postgresql_users_no_log }}"
  become: true
  become_user: "{{ r_postgresql_postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true
  environment:
    PGOPTIONS: "{{ (r_postgresql_postgresql_auth_method == 'scram-sha-256') | ternary('-c password_encryption=scram-sha-256', '') }}"
