---
- name: Centos tasks
  become: true
  environment:
    HTTP_PROXY: "{{ proxy.http }}"
    HTTPS_PROXY: "{{ proxy.https }}" 
  block:
    - name: Add yum repository
      yum_repository:
        name: TD_Agent_Bit
        baseurl: "{{ r_fluentbit_repos[facts.distro_lower][facts.distro_major]['url']|mandatory}}"
        gpgcheck: true
        gpgkey: "{{ r_fluentbit_repos[facts.distro_lower][facts.distro_major]['gpg']|mandatory}}"
        description: Fluentbit repo
        enabled: true
