---
- name: Source td-agent-bit main conf
  template:
    src: td-agent-bit.conf.j2
    dest: /etc/td-agent-bit/td-agent-bit.conf
    mode: 0644
  notify: Restart Fluentbit service

- name: Source additional td-agent-bit conf
  template:
    src: '{{ item.template }}'
    dest: '/etc/td-agent-bit/{{ item.name }}'
    mode: 0644
  with_items: '{{ r_fluentbit_additional_conf_files }}'
  when: r_fluentbit_additional_conf_files | length >0
  notify: Restart Fluentbit service
