---
- name: become
  become: yes
  block:
  - name: Installation
    import_tasks: install.yml
    tags: r_fluentbit_install
  - name: Configuration
    import_tasks: config.yml
    tags: r_fluentbit_config
