---
AppRouter:
  reserved_tables:
    local: 255
    main: 254
    default: 253
    unspec: 0
  sysctl:
    name: router
    priority: "99"
    configs:
      net.core.rmem_max: 67108864
      net.core.wmem_max: 67108864
      net.core.netdev_max_backlog: 250000
      net.core.somaxconn: 4096
      net.ipv4.conf.all.log_martians: 0
      net.ipv4.conf.all.send_redirects: 0
      net.ipv4.conf.all.accept_source_route: 0
      net.ipv4.conf.all.accept_redirects: 0
      net.ipv4.conf.all.secure_redirects: 0
      net.ipv4.conf.all.rp_filter: 2
      net.ipv4.conf.default.rp_filter: 2
      net.ipv4.conf.default.send_redirects: 0
      net.ipv4.ip_forward: 1
      net.ipv4.ip_local_port_range: 10000 65000
      net.ipv4.icmp_echo_ignore_broadcasts: 0
      net.ipv4.tcp_window_scaling: 1
      net.ipv4.tcp_synack_retries: 2
      net.ipv4.tcp_syncookies: 1
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_tw_recycle: 1
      net.ipv4.tcp_fin_timeout: 15
      net.ipv4.tcp_sack: 1
      net.ipv4.tcp_fack: 1
      net.ipv4.tcp_timestamps: 1
      net.ipv4.tcp_keepalive_time: 360
      net.ipv4.tcp_max_syn_backlog: 8192
      net.ipv4.tcp_max_tw_buckets: 5000
      net.ipv4.tcp_fastopen: 3
      net.ipv4.tcp_mem: 25600 51200 102400
      net.ipv4.tcp_rmem: 4096 87380 67108864
      net.ipv4.tcp_wmem: 4096 65536 67108864
      net.ipv4.tcp_mtu_probing: 1
      net.ipv4.tcp_congestion_control: hybla
      # Buffer bloat ftl
      net.ipv4.tcp_ecn: 1
      net.ipv4.tcp_dsack: 1
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.autoconf: 0
      net.ipv6.conf.all.accept_ra: 0
      net.ipv6.conf.default.autoconf: 0
      net.ipv6.conf.default.accept_ra: 0