---
- name: Become
  become: yes
  tags: r_nginx_config_sites
  block:
    - name: Generate sites config
      template:
        src: site.conf.j2
        dest: "{{ r_nginx_config_path }}/sites-enabled/{{ site_config.key }}.site.conf"
        owner: "{{ r_nginx_user }}"
        group: "{{ r_nginx_group }}"
        mode: 0644
      loop: "{{ nginx.sites|default({})|dict2items }}"
      loop_control:
        loop_var: site_config
        label: "{{ site_config.key }}"
      when: not site_config.value.disabled|default(False)
    - name: Remove disabled sites
      file:
        path: "{{ r_nginx_config_path }}/sites-enabled/{{ site_config.key }}.site.conf"
        state: absent
      loop: "{{ nginx.sites|default({})|dict2items }}"
      loop_control:
        loop_var: site_config
        label: "{{ site_config.key }}"
      when: site_config.value.disabled|default(False)
