---
- name: Become
  become: yes
  block:
    - name: Installation
      tags: r_nginx_install
      block:
        - name: Ensure nginx key
          apt_key:
            url: https://nginx.org/keys/nginx_signing.key
            state: present
        - name: Ensure nginx repo
          apt_repository:
            repo: deb http://nginx.org/packages/ubuntu {{ facts.distro_release }} nginx
            filename: nginx-stable
        - name: Ensure package pinning
          copy:
            dest: /etc/apt/preferences.d/99nginx
            content: "Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n"
    - name: Remove
      tags:
        - never
        - ROLE_NGINX_REMOVE
      block:
        - name: Remove nginx repo
          file:
            path: item
            state: absent
          loop:
            - /etc/apt/sources.list.d/nginx-stable.list
            - /etc/apt/preferences.d/99nginx