---
facts:
  system: "{{ ansible_facts['system'] }}"
  os_info: "{{ ansible_facts['system'] }}: {{ ansible_facts['os_family'] }} {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} '{{ ansible_facts['distribution_release']}}'"
  os_dist_ver: "{{ ansible_facts['distribution']|lower }}_{{ ansible_facts['distribution_major_version'] }}"
  distro: "{{ ansible_facts['distribution'] }}"
  distro_lower: "{{ ansible_facts['distribution']|lower }}"
  distro_major: "{{ ansible_facts['distribution_major_version'] }}"
  distro_release: "{{ ansible_facts['distribution_release'] }}"
  local: "{{ ansible_facts['ansible_local'] }}"