---
- name: ({{ project_name}}) Ensure required python modules
  become: yes
  pip:
    name: 
      - python-gitlab
      - python-slugify
      - typing-extensions==3.10.0.0
  environment: 
    HTTP_PROXY: "{{ ((proxy.http is defined) and (not ho_has_internet)) | ternary(proxy.http, None) }}"
    HTTPS_PROXY: "{{ ((proxy.https is defined) and (not ho_has_internet)) | ternary(proxy.https, None) }}"
- name: ({{ project_name }} {{project_source.project.branch|default("default")}}:{{project_source.project.commit|default("latest")}}) Get Project
  get_from_gitlab: "{{ project_source.project }}"
  register: downloaded_source
# - name: Downloaded Fron Gitlab
#   debug:
#     msg: "{{downloaded_source.msg}}"
